---
- yum:
    name: httpd
    state: latest
- service:
    name: httpd
    enabled: true
    state: started
- file:
    path: /var/www/html
    owner: root
    group: webadm
    state: directory
    mode: u=rwx,g=rwx,o=rx,g+s
