---
- yum:
    name: firewalld
    state: latest
- copy:
    src: roles/firewalld/files/ssh.xml
    dest: /etc/firewalld/services
- service:
    name: firewalld
    enabled: true
    state: started
- firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - http
    - https
