---
- name: Port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port"
    insertafter: "^#Port"
    line: "Port 20022"
  notify: restart sshd
- name: LoginGraceTime
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^LoginGraceTime"
    insertafter: "^#LoginGraceTime"
    line: "LoginGraceTime 30"
  notify: restart sshd
- name: PermitRootLogin
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    insertafter: "^#PermitRootLogin"
    line: "PermitRootLogin no"
  notify: restart sshd
- name: PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    insertafter: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: restart sshd
- name: ChallengeResponseAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ChallengeResponseAuthentication"
    insertafter: "^#ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
  notify: restart sshd
- name: PermitEmptyPasswords
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitEmptyPasswords"
    insertafter: "^#PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  notify: restart sshd
- name: PubkeyAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication"
    insertafter: "^#PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
  notify: restart sshd